### PR TITLE
 enhancement/added 10 quotes

### PR DESCRIPTION
**Pull request by 1-SubhamSingh**
Enhances :  #2
Added 10 new quotes to the existing data.

### CODE REVIEW

**Comment by JayShukla8** [comment]
please limit it to your 1 fav quote, i'll merge then.

**Comment by 1-SubhamSingh** [comment]
> please limit it to your 1 fav quote, i'll merge then.

Ok

**Comment by 1-SubhamSingh** [comment]
I have reduced the quotes to one of my fav you can check and merge it.

**Comment by 1-SubhamSingh** [comment]
I have created a new pull request as this was having some conflicts.

**Pull request closed without merging**
