### PR TITLE
UI Enhancements and Quote Copy Functionality Added 

### PR DESCRIPTION
**Pull request by theriturajps**
**Enhancement: Improved Website UI and Added Copy To Clipboard Functionality** :- #14

## 🧑‍💻 Overview
This pull request introduces several enhancements to the website's user interface and functionality aimed at providing a better and more professional user experience.

## 🛠️ Changes Made:
1. **UI Enhancements:**
   - Adjusted font sizes for improved readability.
   - Implemented a box-hover effect for a more engaging visual experience.

2. **New Functionality:**
   - Added a feature that allows users to double-click on a quote to automatically copy it to their clipboard.
    ```js
    quoteBlock.addEventListener('click', function() {
        navigator.clipboard.writeText(quoteText.textContent)
            .then(() => {
                console.log("Quote copied to clipboard!");
            })
            .catch(err => {
                console.log('Error copying text: ', err);
            });
    });
    ```

3. **Data Updates:**
   - Included 8 new quotes in the `data.json` file to enrich the content available on the site.

## Impact
These changes contribute to a more polished and user-friendly interface, while the new quote functionality enhances usability by making it easier for users to share quotes.

## ✔️Checklist
- [x] I have added tests to cover my changes.
- [x] I have updated the documentation (if necessary).
- [x] I have followed the project's code style guidelines.

## Next Steps
Please review the changes and consider merging this pull request to improve the overall user experience of the website.

### CODE REVIEW

**Comment by JayShukla8** [comment]
### Hi @theriturajps!🫡, 
Thank you for taking out the time and for your work on the quote copy feature and box-hover effect🎉. 
They look great, and I’d love to merge them. 
Regarding the font size, I feel that it’s a bit smaller than what we’re going for in our design, and we'd also like a bit more variety in the quotes. Could I ask you to tweak the pull request to include just the quote copy feature and the hover effect for now? That way, I can merge these improvements right away! 😊
Once updated, I'll be happy to merge your changes!✌🏻

**Comment by theriturajps** [comment]
Thank you for the feedback! 😊 I'll make the updates as requested and focus on just the quote copy feature and hover effect for now. I'll tweak the pull request and let you know as soon as it's done so you can merge the changes.

**Comment by theriturajps** [comment]
Hey, I’ve updated the pull request as requested! 🎉 I’ve made changes (increased) the font size, plus I’ve added more variety in the quotes as well. Let me know if everything looks good, and feel free to merge the changes when you're ready! 😊

[Github Pages](https://github.com/theriturajps/Quotes)

**Comment by JayShukla8** [comment]
@all-contributors please add @theriturajps for data and code.

**Pull request merged**
