### PR TITLE
Added search feature

### PR DESCRIPTION
**Pull request by TakangNina**

### CODE REVIEW

**Comment by JayShukla8** [comment]
Hi @TakangNina , this feature is really impressive. I am grateful for the work you've put into this. But there's a small bug. When we select a tag then the appropriate results are shown. That works fine. But when we select "all" after that, then a blank screen is shown. 

https://github.com/user-attachments/assets/5530edbb-122a-4a56-8f6d-b9954b4f1634

If you can resolve that then that would be really great!

**Comment by TakangNina** [comment]
Not a problem I will work to resolve it
Thank you, you rock🔥

**Comment by TakangNina** [comment]
Fixed that can you check please?

**Comment by JayShukla8** [comment]
Done,
Thanks! also the navbar feature is great!

**Pull request merged**
