### PR TITLE
made changes in the background for light and dark mode and added back…

### PR DESCRIPTION
**Pull request by paridhi1509**
made changes to the background of the dark and light mode by changing background to soothing gradients and added some images on it according to the background.

### CODE REVIEW

**Comment by JayShukla8** [comment]
image
here's image for reference.

**Comment by paridhi1509** [comment]
I could do a coffee stained paper background and can change the droplets to mug stains?

**Comment by JayShukla8** [comment]
Yes! that would look nice. What do you think?

**Comment by paridhi1509** [comment]
Found a better idea 
Just gonna put the PR 
Check it out once

**Comment by paridhi1509** [comment]
Should i open a new PR there as i am not able to merge in this one?

**Comment by JayShukla8** [comment]
Yes this looks nice, Thanks! 
I'll apply other styling changes later.

**Pull request merged**
