### PR TITLE
Chibuike 19/fix overlaping content

### PR DESCRIPTION
**Pull request by chibuike-19**
Fixed overlapping text in quote block and added ellipsis icon to toggle visibility of copy, share and sound icons #128

### CODE REVIEW

**Comment by JayShukla8** [comment]
Hii, there have been some changes. Can you resolve the conflicts? also i already added your quote so no need for that here. Thanks!

**Comment by chibuike-19** [comment]
Sure @JayShukla8. Fixing the conflicts now

**Comment by chibuike-19** [comment]
Conflicts fixed!

**Comment by JayShukla8** [comment]
Thanks!

**Pull request merged**
