### PR TITLE
star-rating feature #24

### PR DESCRIPTION
**Pull request by Mukesh-ghildiyal**
#40  completed check it and merge it.
Medi-Connect - Google Chrome 01-10-2024 01_37_44 PM

### CODE REVIEW

**Comment by KorryKatti** [comment]
yo @Mukesh-ghildiyal just wanted to know where are you storing the ratings ?

**Comment by Mukesh-ghildiyal** [comment]
right now from nowhere but i can store it in local storage if you allow

**Comment by KorryKatti** [comment]
i am not the maintainer i was just curious

**Comment by JayShukla8** [comment]
hii @Mukesh-ghildiyal,

I am thankful and appreciate your willingness to contribute and the time and thought you’ve put into this idea.

However, I’ve decided to keep the project more focused on displaying quotes without adding a review or rating system for now. The simplicity of the current setup is something I’d like to maintain, as it aligns with the original goal of the project.

Thanks again for your understanding and your effort!

**Pull request closed without merging**
