### PR TITLE
Added some famous quotes from different persons

### PR DESCRIPTION
**Pull request by vigneshs-dev**
As you @JayShukla8  asked, I added some more Quotes from different persons.

### CODE REVIEW

**Comment by vigneshs-dev** [comment]
Is there any problem with my Quotes?  I updated the Quotes as per your request. What was the problem @JayShukla8 ?

**Comment by JayShukla8** [comment]
you removed someone else's quote.

**Comment by vigneshs-dev** [comment]
> you removed someone else's quote.

No. I removed no one's quote. When I try to add some quotes, it already present in the data. I checked them with Ctrl + F key. I added the new quotes only. I do nothing other than that. You can see the commit process in the below [this](https://github.com/JayShukla8/Quotes/pull/31/commits/01c0a8dc79e8e61565192539b902bf1a8d0d0998) link also

**Comment by vigneshs-dev** [comment]
@JayShukla8 
I am really sorry.

```
{
      "quote": "The best among you is the one who doesn’t harm others with his tongue and hands.",
      "author": "Prophet Muhammad",
      "source": "Sahih al-Bukhari"
}
```
This is the missed quote. This was added when I was working in my local repository. Now I added this also along with my new Quotes. Can I create a new Pull Request now?

**Comment by JayShukla8** [comment]
yes

**Comment by vigneshs-dev** [comment]
> yes

I have Opened a Pull Request by following your guidance. Please merge it with the main branch. Thankyou.

**Pull request closed without merging**
