### PR TITLE
improve scroll bar and preloader

### LINKED ISSUE #174: [Feature Request]: Improve Scroll Bar and Preloader
### Is there an existing issue for this?

- [X] I have searched the existing issues

###  Description 

The current Scroll bar Ui has a very basic layout and outdated design and site Loading has no preloader. The screen becomes blank when the website loads. Enhancing the colour scheme of Thumb and Track, improving the preloader and modernizing the scroll bar design would greatly improve the user experience and website presentation

**Describe the solution you'd like**

- Redesign the Scroll bar and preloader for better visual appeal.
- Improving the scroll bar thump and track.
- Improving the preloader.

**Describe alternatives you've considered**

**Without Preloader and without improvement in Scroll BAR**

Screenshot 2024-10-07 135253

https://github.com/user-attachments/assets/47378d83-5413-4422-9d5d-e7ac479d41c0

**Preloader Mockup**

https://github.com/user-attachments/assets/581ba556-6358-4767-88ee-db82b2b33997

**Additional context**
@JayShukla8   can you assign this issue to me with labels "gssoc-ext" with levels ,"hacktoberfest-accepted";

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by VidhanThakur09**
### Related Issue

Issue Fixed: #174  

### Description

Styling has been applied to the preloader and scroll bar. The preloader and Scroll bar is present on all pages of the website with styling. The scroll bar behaviour has been improved and the thumb and track have been redesigned, resulting in improved scroll behaviour.

*Improvements:*

1. *Optimized Preloader:* Enhanced the preloader animation on the landing page to improve user experience.

2. *Revamped Preloader Design:* Redesigned the preloader with modern CSS styling to enhance visual appeal.

3. *Dedicated Preloader Script and StyleSheet:* Created a separate JavaScript file named `"preloader.js"` to manage the preloader functionality and CSS file named `" preloaderStyle.css"` to enhance the styling and functionality, ensuring better code organization and maintainability.

## How Has This Been Tested? 

The program was tested locally on a machine using the Chrome browser. To verify the changes, the website was loaded after the modifications were made. This involved manually inspecting the visual elements and functionally testing various user interactions to ensure the changes were implemented correctly.

## Screenshots 📷

**Before changes** 

https://github.com/user-attachments/assets/59aac5fb-6f00-498e-8c8b-b0b2bc9e7c94

**After adding preloader**

https://github.com/user-attachments/assets/45f3ae4f-a598-4b3d-96a4-c0e2f57e10f5

**After improving scroll bar**

https://github.com/user-attachments/assets/bc20a5b9-d026-41c1-b31f-d880ec58822f

### CODE REVIEW

**Comment by VidhanThakur09** [comment]
@JayShukla8 Could you please review this pull request?

**Comment by JayShukla8** [comment]
Yes i did. There are several things not right here. Firstly there are conflicts in the pr, secondly the loading page is not displayed properly. I ran your code on my local machine and saw that the website looks better without the loading screen. Also the orientation and padding for the quotes is not proper and looks haphazard. Sorry but i will not be able to merge this request. If you want to contribute, you can add your fav quote and update the data.json. Thanks for your time.

**Comment by VidhanThakur09** [comment]
Apologies for any inconvenience caused. May I kindly inquire if it would be possible to include quotes from the Bhagavad Gita?

**Comment by JayShukla8** [comment]
Sure, there's no problem with that. Please make a new pr for that.
.
Also i am attaching below a video for reference of how the loading screen is not proper + the quotes padding is gone. You can compare it with current website to see the difference.

https://github.com/user-attachments/assets/7d54692b-4e23-4510-9fca-dac6257076b8

**Pull request closed without merging**
