### PR TITLE
Add like functionality

### PR DESCRIPTION
**Pull request by tanish35**
image

Upon liking the quote the color turns red

image

Even after reloading the site the liked quotes still remain liked

### CODE REVIEW

**Comment by tanish35** [comment]
Pls add hacktoberfest-accepted label

Solves #121 

Also if you want I can add a seperate issue where the likes are for each quote are stored in a cdn server and is retrieved when the website is reloaded

**Comment by tanish35** [comment]
image

Ok so my dark reader was turned on so the background wasn't visible this is the one without dark reader on

**Comment by JayShukla8** [comment]
this will be different for every user right? user A won't be able to see what the user B has liked. Right? also what's different when you use a CDN server?

**Comment by tanish35** [comment]
Yes it is different for every user currently. User B won't be able to see what User A has liked. It is currently happening in localstorage

If you want other users to also be able to see who has liked what then i can do that by creating a seperate issue. The likes can get stored in a redisdb and it will retrieve that

**Comment by JayShukla8** [comment]
No i think the local storage is fine. Thanks! I'll merge it soon.

**Pull request merged**
