### PR TITLE
Added a new quote, didn't change anything else

### PR DESCRIPTION
**Pull request by Asmi1108**

### CODE REVIEW

**Comment by JayShukla8** [comment]
great choice!

**Comment by Asmi1108** [comment]
> great choice!

Thanks! 
Also, can one add as many as quotes they want to?

**Comment by JayShukla8** [comment]
No, we've limited it to 1 per person as of now. But if you have another good one in mind, feel free to make a pr. We can make some adjustments.

**Comment by Asmi1108** [comment]
> No, we've limited it to 1 per person as of now. But if you have another good one in mind, feel free to make a pr. We can make some adjustments.

Thanks for letting me know! The latter works just well for me cuz I've gotten a few on my fingertips and would love to share! 😄

**Pull request merged**
